version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: tooling/docker/Dockerfile
      target: dev
    volumes:
      - ./:/usr/src/app
    environment:
      PORT: 7000
      NODE_ENV: dev
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/lanchonete?schema=public
    ports:
      - 7000:7000
    command: npm run dev
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanchonete
    ports:
      - 5432:5432

networks:
    default:
        name: lanchonete-network
